---
kind: pipeline
name: grimd

platform:
  os: linux
  arch: amd64

steps:
- name: docker
  image: plugins/docker
  settings:
    password:
      from_secret: docker_password
    repo: titouanco/grimd
    tags: latest
    username:
      from_secret: docker_username

...
